fix: avoid nesting button in code block
readmeio/markdown pull request #587
Opened 2022-09-21 22:20 UTC by ilias-t

[![PR App][icn]][demo] | Fix RM-5222
:-------------------:|:----------:

## 🧰 Changes

This is a bit more semantic and therefore helps Localize, which we use for translations, parse our html correctly.

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

2022-09-21 22:21 UTC, kellyjosephprice approved these changes
🤯

2022-09-21 22:58 UTC, rafegoldberg requested changes
Have you checked that this doesn't screw up the absolute positioning on code _blocks?_ (versus online code _snippets_?)

2022-09-21 23:00 UTC, rafegoldberg approved these changes
Oh you did (sorry, on my phone and I forgot to uncollapse the full PR description before I looked at the code!)

2022-09-21 23:00 UTC, ilias-t commented
> Have you checked that this doesn't screw up the absolute positioning on code _blocks?_ (versus online code _snippets_?)

If I understand the question, yes I checked, there's a screenshot of both in the PR description

2022-09-21 23:20 UTC, merged

2022-09-22 01:02 UTC, rafegoldberg commented
<img align="right" height="100" src="https://user-images.githubusercontent.com/886627/87183626-529d9580-c29b-11ea-8c54-5ca58a1f4a77.png" />

## This PR was released!

🚀 Changes included in [<b>v6.52.1</b>](/readmeio/markdown/releases/tag/v6.52.1)
<br>