feat: tabs component
readmeio/markdown pull request #948
Opened 2024-08-06 22:18 UTC by trishaprile

[![PR App][icn]][demo] | Fix RM-9809
:-------------------:|:----------:

## 🧰 Changes

<img width="500" alt="image" src="https://github.com/user-attachments/assets/5a72b218-b193-4aa3-91c5-590a5859e90f">

## 🧬 QA & Testing

- [Broken on production][prod].
- [Working in this PR app][demo].

[demo]: https://markdown-pr-PR_NUMBER.herokuapp.com
[prod]: https://SUBDOMAIN.readme.io
[icn]: https://user-images.githubusercontent.com/886627/160426047-1bee9488-305a-4145-bb2b-09d8b757d38a.svg

2024-08-08 22:45 UTC, rafegoldberg requested changes

2024-08-08 22:45 UTC, rafegoldberg commented on components/Tabs/style.scss
> +  .nav {
Small detail: these child element classes should use BEM-style selectors, so `.TabGroup-nav` and `.TabGroup-tab` [per our SCSS selector conventions](https://next.readme.ninja/ui/#/Conventions/Writing%20CSS "Scroll to the bottom of this page.")!

2024-08-08 23:35 UTC, kellyjosephprice commented
Oh, you can merge this against `next` now!

2024-08-09 03:28 UTC, rafegoldberg approved these changes
Yay; thanks for the quick rewrite @trishaprile!

2024-08-09 19:48 UTC, merged

2024-08-12 22:53 UTC, rafegoldberg commented
<img align="right" height="100" src="https://user-images.githubusercontent.com/886627/87183626-529d9580-c29b-11ea-8c54-5ca58a1f4a77.png" />

## This PR was released!

🚀 Changes included in [<b>v7.1.0</b>](/readmeio/markdown/releases/tag/v7.1.0)
<br>